### ISSUE TITLE
Git Pull Asking For Username

### ISSUE THREAD

**Issue by royaltongue** [haq/microsoft-rewards-bot#3]
When trying to run the bot, I get an prompt saying: `Username for 'https://github.com':`

It also seems like Github is failing to create your image: https://github.com/haq/microsoft-rewards-bot/actions/workflows/docker-publish.yml

And I would assume this is all because farshadz repo has been removed: https://github.com/farshadz1997/Microsoft-Rewards-bot

Simply commenting `git pull > /dev/null` out of my script solves the issue for me (for now, anyway), but that wouldn't be possible for people who use the container as-is

**Comment by haq** [comment]
Yes, I noticed this issue when the workflow errored out. 

Removing `git pull > /dev/null` from `entrypoint.sh` will allow the script to run, but you will be one week old code. (since the image is only updated once a week)

I could migrate to his GitLab repo https://gitlab.com/farshadzargary1997/Microsoft-Rewards-bot, but I am not sure how up to date it is.

**Comment by royaltongue** [comment]
Based on [his commits](https://gitlab.com/farshadzargary1997/Microsoft-Rewards-bot/-/commits/master), it seems like it's updated very regularly and as recent as last week. Using that repo instead would probably be a good bet

**Comment by haq** [comment]
Sounds good. I have updated the docker image. 👍
